[package]
name = "optimize_png"
version = "1.1.0"
authors = ["Redwarp <redwarp@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = "3.0"
oxipng = "5.0"
