[package]
name = "optimize_png"
version = "1.2.1"
authors = ["Redwarp <redwarp@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = "3.2.20"
oxipng = "5.0.1"
